### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by basvdberg** [nicholas-ross/SSMS-Schema-Folders#3] opened 2018-03-01 15:12 UTC
Hi, 
I installed your extension in SSMS 2017. Also applied the registry fix, but nothing happens. 
There is a Schema Folders option under SQL SERver Object Explorer, but it gives:
An error occurred loading this property page. 

How can I debug this ?

Bas

Microsoft SQL Server Management Studio						14.0.17213.0
Microsoft Analysis Services Client Tools						14.0.1016.232
Microsoft Data Access Components (MDAC)						6.3.9600.17415
Microsoft MSXML						3.0 5.0 6.0 
Microsoft Internet Explorer						9.11.9600.18921
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.9600

**Comment by nicholas-ross** [comment] 2018-03-02 03:08
This is usually caused by windows security blocking dll files downloaded from the internet.

After downloading, you need to right click on the zip file and go to properties. You should then see a button or tick box to unblock.

After unblocking you can then extract the files.

You can also unblock the individual dll files that you have already extracted. You can't unblock multiple files at once and need to do them individually, which is why I recommend unblocking the zip instead.

If this doesn't solve the issue then we will need to get the ssms log file.

**Comment by cmullican** [comment] 2018-05-24 20:58
I had this issue, too, and this fixed it.  The relevant part of the installation instructions: 

> Depending on your web browser, you may need to unblock the zip file before extracting. Right click on the zip file and select Properties. If you see an Unblock button or checkbox then click it.

was confusing, because my browser (Chrome) also blocked the download, and I thought that kind of block was what this referred to. I suggest making it more clear that this should be done in Windows Explorer, after the file has been downloaded, something like:

> You may need to unblock the zip file before extracting. Right click on the zip file in Windows Explorer and select Properties. If you see an Unblock button or checkbox then click it.

**Comment by nicholas-ross** [comment] 2018-06-28 06:29
@cmullican Thank you for your feedback. I have updated the documentation with your suggestion. I am leaving the issue open because this is the most common issue.

**Comment by yabdulkadir** [comment] 2018-07-26 22:07
I had the same issue. unblocking the zip file did not work for me. I had to unblock each file one by one. Since there are not that many files, I unblocked all of them one by one.

**Comment by joelmaxuel** [comment] 2018-11-02 11:05
Deployed in two places, and encountering the issue with one of the deployments.  All files have been unblocked, but the issue still exists (on the x64 implementation).  Schema nodes do not appear nor does the "Schema Folders" option appear (at all - not even a blank placeholder under "SQL Server Object Explorer")

Versions of the system in question:

Microsoft SQL Server Management Studio 11.0.6020.0
Microsoft Analysis Services Client Tools	11.0.6020.0
Microsoft Data Access Components (MDAC) 6.1.7601.17514
Microsoft MSXML	3.0 6.0 
Microsoft Internet Explorer	9.11.9600.18920
Microsoft .NET Framework	4.0.30319.42000
Operating System	6.1.7601 (x64)

Anything different relevant to the working implementation:

Microsoft MSXML 3.0 4.0 5.0 6.0 
Microsoft .NET Framework	4.0.30319.36441
Operating System	6.1.7601 (x86)

**Comment by Ossy81** [comment] 2018-12-03 13:59
> Hi,
> I installed your extension in SSMS 2017. Also applied the registry fix, but nothing happens.
> There is a Schema Folders option under SQL SERver Object Explorer, but it gives:
> An error occurred loading this property page.
> 
> How can I debug this ?
> 
> Bas
> 
> Microsoft SQL Server Management Studio	14.0.17213.0
> Microsoft Analysis Services Client Tools	14.0.1016.232
> Microsoft Data Access Components (MDAC)	6.3.9600.17415
> Microsoft MSXML	3.0 5.0 6.0
> Microsoft Internet Explorer	9.11.9600.18921
> Microsoft .NET Framework	4.0.30319.42000
> Operating System	6.3.9600

Bas did youfind a fix for this issue? Think the other are a bit confused about the problem. Problem is not related to the download of the file.
File was downloaded and extracted to the right filder, but somehow the option is not appearing in SSMS... Any idea how to solve this?

**Closed** 2023-05-26 01:26 UTC
