### ISSUE TITLE
Not able to see the schema folders after a session

### ISSUE THREAD

**Issue by gvenkat5** [nicholas-ross/SSMS-Schema-Folders#35] opened 2023-06-20 13:26 UTC
I have a situation where I was able to successfully installed the add-in and it worked fine. However whenever I close and re-open the session, just for one database I'm not able to get the folder view to show up on start up. However if I refresh it shows up again.  Here are some screenshots attached.

First screenshot shows when I open the ssms and when i expand tables, it's not under the folders. Second screen shot shows how the other database it is. 

The final screen shot shows once i hit the refresh button how they all show as a folder. Not sure if this is some setting I'm missing

![ssms_before1](https://github.com/nicholas-ross/SSMS-Schema-Folders/assets/137184690/6a2b8f43-e9e3-4e8c-b87c-4fcf8d84c966)
![ssms_before2](https://github.com/nicholas-ross/SSMS-Schema-Folders/assets/137184690/09686a3a-8011-49f7-b99b-e8ef6078a693)
![ssms_after](https://github.com/nicholas-ross/SSMS-Schema-Folders/assets/137184690/7b3c7b5c-9d87-48b2-85e1-381b050b7398)

**Comment by nicholas-ross** [comment] 2023-06-21 04:45
Go to `Tools > Options > SQL Server Object Explorer > Schema Folders` and change the `Folder Level 2 > Folder Type` from `Alphabetical` to `None`.

The alphabetical option isn't helpful when the names are prefixed with the object type. I think I will change the default value for this setting in the next release.

If this doesn't solve the issue then are you connecting to an Azure SQL DB or is SSMS on a VM with only one cpu core?

**Comment by gvenkat5** [comment] 2023-06-21 13:30
I don't think that is fixing my issue. I'm connecting to an Azure SQL DB.

**Comment by gvenkat5** [comment] 2023-06-27 13:25
> Go to `Tools > Options > SQL Server Object Explorer > Schema Folders` and change the `Folder Level 2 > Folder Type` from `Alphabetical` to `None`.
> 
> The alphabetical option isn't helpful when the names are prefixed with the object type. I think I will change the default value for this setting in the next release.
> 
> If this doesn't solve the issue then are you connecting to an Azure SQL DB or is SSMS on a VM with only one cpu core?

Hey This did not fix my issue. Any suggestions to this?

**Comment by nicholas-ross** [comment] 2023-07-03 04:39
I finally got access to an Azure SQL instance I could test with and have identified the cause. It might take a while before I can write a proper fix but I do have a workaround.

In the options change `Unresponsive timeout` to 3000. If you still have the problem then you can increase the value even more.

**Comment by nicholas-ross** [comment] 2023-07-03 04:44
Closing as duplicate of #33.

**Closed by nicholas-ross** 2023-07-03 04:44 UTC
Labels: duplicate

**Comment by gvenkat5** [comment] 2023-07-06 18:57
That may have just fixed it for me.
